# vim: filetype=config
include-file = "/home/cribz/.config/polybar/colors.ini"
include-file = "/home/cribz/.config/polybar/main-bar.ini"
include-file = "/home/cribz/.config/polybar/settings.ini"
include-file = "/home/cribz/.config/polybar/modules.ini"
