# font-0 = CaskaydiaCove Nerd Font:style=Regular:pixelsize=11:antialias=true;2.5
# font-1 = Material Design Icons:style=Regular:pixelsize=11:antialias=true;2.5
font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=20;3
font-1 = JetBrainsMono Nerd Font:size=22;4
font-2 = Material Design Icons:style=Regular:size=20;3
font-3 = unifont:fontformat=truetype:size=17;3
